insert into TipoSensores (tipoSensorId, nomeTecnico, parametroMedido) values(1, 'DHT22','Temperatura e Umidade')
insert into TipoSensores (tipoSensorId, nomeTecnico, parametroMedido) values(2, 'DHT11','Temperatura e Umidade')
insert into TipoSensores (tipoSensorId, nomeTecnico, parametroMedido) values(3, 'FotoSensor','Luminosidade')
insert into TipoSensores (tipoSensorId, nomeTecnico, parametroMedido) values(4, 'RTC','Data e o horário')
insert into TipoSensores (tipoSensorId, nomeTecnico, parametroMedido) values(5, 'DHT33','Temperatura e Umidade')